### ISSUE TITLE
UseShortCircuitOperator Lambda Expression Error

### ISSUE THREAD

**Issue by ThatShawGuy** [ThatShawGuy/VBSharper#2]
Received a NullReferenceException while running R# in Internal mode. the UseShortCircuitOperatorsDaemonStageProcess is not processing lambda expressions correctly.

#### Stack Trace
>  at VBSharper.Plugins.QuickFixes.UseShortCircuitOperators.UseShortCircuitOperatorsQuickFixHelper.<GetTreeNodeDocumentRanges>d__2.MoveNext()
>     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>     at VBSharper.Plugins.QuickFixes.UseShortCircuitOperators.UseShortCircuitOperatorsDaemonStageProcess.Execute(Action`1 committer)
>     at JetBrains.ReSharper.Daemon.Impl.DaemonProcessBase.<>c__DisplayClass11.<DoHighlighting>b__4(IDaemonStage stage)

**Comment by ThatShawGuy** [comment]
Fixed in v1.3.0
